config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: %i[create destroy]

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, only: :show
    end
  end

  resources :users, only: %i[create show edit update] do
    resources :friendships, only: %i[create destroy]
  end

  get :login, to: 'sessions#new'
  root 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
# frozen_string_literal: true

class Friendship < ApplicationRecord
  belongs_to :friend_a, class_name: :User
  belongs_to :friend_b, class_name: :User

  validates :friend_a, :friend_b, presence: true
  validate :already_friends

  scope :for_id, lambda { |friend_a, friend_b|
                  where(
                    '(friend_a_id = ? AND friend_b_id = ?) OR (friend_a_id = ? AND friend_b_id = ?)',
                    friend_a, friend_b, friend_b, friend_a
                  )
                }

  private

  def already_friends
    friendship = Friendship.for_id(friend_a.id, friend_b.id)
    return if friendship.blank?

    errors.add(:base, "You are already friends with #{friend_b.email}")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  ROLES = %w[friend].freeze

  # associations
  has_one :invited_by_user, ->(user) { unscope(:where).where('users.id = ?', user.invited_by_id) }, class_name: :User
  has_many :friendships, lambda { |user|
                           unscope(:where)
                             .where('friendships.friend_a_id = ? OR friendships.friend_b_id = ?',
                                    user.id, user.id)
                         }
  has_many :friends, lambda { |user|
                       unscope(:where)
                         .where(id: user.friendships.pluck(:friend_a_id, :friend_b_id).flatten.uniq -
                                Array.wrap(user.id))
                     }, class_name: :User

  # validations
  validates :first_name, :last_name, :email, presence: true
  validates :first_name, :last_name, length: { in: 3..50 }
  validates :email, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate :validate_roles

  def friendship(friend)
    # The pair is always unique.
    Friendship.for_id(id, friend.id).first
  end

  private

  def validate_roles
    return unless (roles - ROLES).any?

    errors.add(:roles, 'Roles not included in list')
  end
end

app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < ApplicationController
      include ExceptionHandler
      include BaseHandler

      protected

      def show
        render json: resource
      end

      def resource
        @resource ||= model.find(params[:id])
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class UsersController < BaseController
      actions :show
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit
  add_flash_types :error, :warning, :success
  helper_method :logged_in?, :current_user

  def current_user
    return unless session[:user_id]

    User.find(session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def authorized
    redirect_to login_path unless logged_in?
  end
end

app/controllers/concerns/base_handler.rb
# frozen_string_literal: true

module BaseHandler
  extend ActiveSupport::Concern

  private

  def model
    controller_name.camelize.singularize.constantize
  end

  class_methods do
    def actions(*actions)
      send :public, *actions
    end
  end
end

app/controllers/concerns/exception_handler.rb
# frozen_string_literal: true

module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |_e|
      render json: { message: 'Record not found.' }, status: :not_found
    end
  end
end

app/controllers/friendships_controller.rb
# frozen_string_literal: true

class FriendshipsController < ApplicationController
  before_action :authorized

  def create
    friendship = Friendship.new(friend_a_id: current_user.id)
    authorize friendship

    friendship_form = CreateFriendshipForm.new(friendship, permitted_params)
    friendship_form.generate

    if friendship_form.errors.blank?
      redirect_to current_user, success: I18n.t('success.friends.create')
    else
      redirect_to current_user, error: friendship_form.errors.to_sentence
    end
  end

  def destroy
    friendship = Friendship.find(params[:id])
    authorize friendship

    if friendship.destroy
      redirect_to current_user, warning: I18n.t('warnings.friends.destroy')
    else
      redirect_to current_user, error: friendship.errors
    end
  end

  private

  def permitted_params
    params.permit(:first_name, :last_name, :email, :password, roles: [])
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def new
    redirect_to current_user if session[:user_id]
  end

  def create
    return unless user.authenticate(params[:password])

    session[:user_id] = user.id
    redirect_to user
  end

  def destroy
    session[:user_id] = nil

    redirect_to login_path, warning: I18n.t('warnings.sessions.destroy')
  end

  private

  def record_not_found
    redirect_to login_path, error: I18n.t('errors.sessions.find')
  end

  def user
    @user ||= User.find_by!(email: params[:email])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true
class UsersController < ApplicationController
  before_action :authorized, only: %i[show edit update]

  def create
    new_user = User.new(user_params)

    if new_user.save
      session[:user_id] = new_user.id
      redirect_to new_user
    else
      redirect_back fallback_location: root_path, error: new_user.errors.full_message
    end
  end

  def show
    @presenter = UserPresenter.new(user)
  end

  def edit; end

  def update
    authorize user

    if user.update(user_params)
      redirect_to user, success: I18n.t('success.users.update')
    else
      redirect_back fallback_location: '/', error: user.errors.full_message
    end
  end

  private

  def user_params
    params.permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def user
    @user ||= authorize current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_msg
    flash.each_with_object([]) do |(type, message), flash_messages|
      text = "<div class='flash-msg'>
                <div class='card text-white rounded-3 bg-#{type == 'error' ? 'danger' : type} mb-3 friend-card'>
                  <div class='card-body'>
                    <h4 class='card-title'>#{message} <i class='bi bi-emoji-#{emoji(type)}'></i></h4>
                  </div>
                </div>
              </div>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end

  def emoji(type)
    type == 'success' ? 'smile' : 'neutral'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PressableTestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'shared/navbar'%>
      <%= flash_msg %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark site-navbar">
  <% if session[:user_id] %>
    <%= link_to "Pressable", user_path(current_user), class: "navbar-brand" %>
  <% else %>
    <%= link_to "Pressable", root_path, class: "navbar-brand" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <% if session[:user_id] %>
      <ul class="navbar-nav" id="nav-dropdown">
        <li class="nav-item dropdown mr-sm-2">
          <a class="nav-link dropdown-toggle mr-sm-2" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.first_name%>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Edit profile", edit_user_path(current_user), class:"dropdown-item" %>
            <%= button_to "Log out", sessions_path, class:"dropdown-item", method: 'delete' %>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/users/_edit.html.erb
<%= form_with url: user_path(current_user), method: :patch do |f| %>
  <div class="form-row">
    <div class="col">
      <%= f.text_field :first_name, placeholder: "First name", class: "form-control", required: true, value: current_user.first_name %>
    </div>
  </div>
  <br>
  <div class="form-row">
    <div class="col">
      <%= f.text_field :last_name, placeholder: "Last name", class: "form-control", required: true, value: current_user.last_name %>
    </div>
  </div>
  <br>
  <div class="form-row">
    <div class="col">
      <%= f.text_field :email, placeholder: "sample@email.com", class: "form-control", required: true, value: current_user.email%>
    </div>
  </div>
  <br>
  <%= f.submit "Update Account", class: "btn btn-primary" %>
<% end %>

app/views/users/_friend_form.html.erb
<%= form_with url: user_friendships_path(current_user.id) do |friend| %>
  <div class="form-row">
    <div class="col">
      <%= friend.text_field :first_name, placeholder: "First name", class: "form-control", required: true %>
    </div>
  </div>
  <br>
  <div class="form-row">
    <div class="col">
      <%= friend.text_field :last_name, placeholder: "Last name", class: "form-control", required: true %>
    </div>
  </div>
  <br>
  <div class="form-row">
    <div class="col">
      <%= friend.text_field :email, placeholder: "sample@email.com", class: "form-control", required: true %>
    </div>
  </div>
  <br>
  <%= friend.hidden_field :password, value: 'password' %>
  <%= friend.hidden_field 'roles[]', value: 'friend' %>
  <%= friend.submit "Invite friend", class: "btn btn-success"%>
<% end %>

app/views/users/_friend_list.html.erb
<table class="table table-striped" id ="friend-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Friends since</th>
      <th scope="col">Delete friend</th>
    </tr>
  </thead>
  <tbody>
    <% if current_user.friends.blank?%>
      <tr>
        <td colspan="5" class="table-active" id="no-friends">You have no friends.</td>
      </tr>
    <% else %>
      <% current_user.friends.each_with_index do |friend, index| %>
        <tr>
          <td><%= index + 1%></td>
          <td><%= friend.first_name %></td>
          <td><%= friend.last_name %></td>
          <td><%= @presenter.friendship_duration(friend) %></td>
          <td>
            <%= button_to user_friendship_path(current_user.id, current_user.friendship(friend).id), method: :delete, class: "btn btn-danger"  do %>
                <span class="bi bi-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/_password.html.erb
<%= form_with url: user_path(current_user), method: :patch do |f| %>
  <div class="form-row">
    <div class="col">
      <%= f.password_field :password, placeholder: "*********", class: "form-control", required: true %>
    </div>
  </div>
  <br>
  <div class="form-row">
    <div class="col">
      <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control", required: true %>
    </div>
  </div>
  <br>
  <%= f.submit "Update Password", class: "btn btn-warning" %>
<% end %>

app/views/users/edit.html.erb
<div class="card mt-5" id ="friend-form">
  <div class="card-body">
    <h2 class="card-title">Edit profile</h5>
    <%= render 'edit'%>
  </div>
</div>
<div class="card mt-5" id ="friend-form">
  <div class="card-body">
    <h2 class="card-title">Update password</h5>
    <%= render 'password'%>
  </div>
</div>

app/views/users/show.html.erb
<% if @user.roles.include?('friend') && current_user.friends.any?%>
  <div class="card text-white bg-success mb-3 friend-card">
    <div class="card-body">
      <h4 class="card-title">
        <%= @presenter.invited_by %>
        <i class="bi bi-emoji-smile"></i>
      </h4>
    </div>
  </div>  
<% end %>
<div class="card mt-3" id ="friend-form">
  <div class="card-body">
    <h2 class="card-title">Invite a friend</h5>
    <%= render 'friend_form'%>
  </div>
</div>
<%= render 'friend_list'%>